---
galaxy_info:
  author: "VM Workstation Setup"
  description: "Git configuration tasks"
  company: ""
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - git
    - configuration
    - version-control 