---
galaxy_info:
  author: "VM Workstation Setup"
  description: "Claude Code installation and configuration"
  company: ""
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - claude
    - ai
    - coding 