# Generated By: Cursor (Claude Sonnet 4)
# Makefile for VM Workstation Setup Ansible Playbook

# Include modular makefiles
include make/env.mk
include make/ansible.mk
include make/lint.mk
include make/config.mk

.DEFAULT_GOAL := help
.PHONY: help

# Variables
ANSIBLE_DIR := ansible
PLAYBOOK := $(ANSIBLE_DIR)/site.yml
INVENTORY := localhost,
CONNECTION := local
TAGS ?= 
LIMIT ?=

# Python virtual environment
VENV_DIR ?= .venv
PYTHON := $(VENV_DIR)/bin/python
PIP := $(VENV_DIR)/bin/pip
UV := $(VENV_DIR)/bin/uv

# Project-local Ansible collections location
COLLECTIONS_DIR := $(CURDIR)/collections

# Colors for output
BLUE := \033[34m
GREEN := \033[32m
YELLOW := \033[33m
RESET := \033[0m

# Export common environment for all recipes
export PATH := $(CURDIR)/$(VENV_DIR)/bin:$(PATH)
export ANSIBLE_CONFIG := $(CURDIR)/$(ANSIBLE_DIR)/ansible.cfg
export ANSIBLE_COLLECTIONS_PATH := $(COLLECTIONS_DIR)

help: ## Display this help message
	@echo "VM Workstation Setup - Ansible Playbook"
	@echo "========================================"
	@echo ""
	@echo "Available targets:"
	@echo ""
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
