---
galaxy_info:
  author: "VM Workstation Setup"
  description: "Samba file sharing tasks"
  company: ""
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - samba
    - file-sharing
    - windows
  reminders: "run 'make samba-password' to set your Samba password" 