---
# Git configuration tasks

- name: Configure git settings (preserves existing user config)
  community.general.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop: "{{ git_config }}"
