---
galaxy_info:
  author: "VM Workstation Setup"
  description: "Package installation tasks"
  company: ""
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - packages
    - installation
    - dnf 