---
galaxy_info:
  author: "VM Workstation Setup"
  description: "Files deployment tasks - dumb copy operations"
  company: ""
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - files
    - configuration
    - shell
  reminders: "restart your terminal or run 'source ~/.bashrc'" 