---
galaxy_info:
  author: "VM Workstation Setup"
  description: "Install GNOME Shell extensions for the current user by downloading zips"
  company: ""
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - gnome
    - extensions
    - desktop
  reminders: "logout and login again to apply all GNOME Extensions" 